language: go
dist: xenial
sudo: false
services: [docker]

matrix:
  include:
    - os: linux
      go: 1.14.x

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: lYQO2KgkUTGvyDm6FOU2/Ny6R06BsTMsArwkHGiM2Uc7FxvtHQm8Ko8vtflIA9f4EW/WBgbIfxTRI9w++UoGP6YmyXXln5jM07qGbf49uOq2i00iIdc2xp13MC2TQfCtqKhPUQXlAZASViYI+E7uVibxY5hZZtrs8gGbaGYO+5Tlf3qeKUVQRf61ylbGc5/CmYIjLtUOUcRNPfrhLRIXF/EReE0IV80EJb/gd/HWiszYiv2hdwfWclXAkZk8vYjG3znnGjhRjEdDjJX65Kmr7YYZnngp4qQCumyFArH3yGW3xpR8hs8ra5lWJtMNW/UdFqiq/RM6YNPuO81LCxgwPoIjS2VKqlIOUHAV+hCyrSTUjZY916VUlSuMYhwFvRddkIbS3D6oSdiWZq3XMUQjr0PjK6VOgSjMAoyd9lWlNC/NlPi9o+JtM3tHqJb4v7DJkQIz6ffBdKLmXdv/0dXpTkafFArrQyweuwluvdbwShyIlSM9B360j6p0azLYDULsC39g8RlnQMOB/lZ7xSpVqd8mT9NRfp1O8tjwtu+DqvLskjhRUpYrKF7/58g8yKZGt/yrgBhBmghXGq9rq5ce4fCVUGc5oOvswmDHHrHwNJJIp6mGlkdJUgpXaw3YDfajIma2H8Vrugx7fA1SPSWXH7lok3pe/9a3rPb/Q1Ov6Fo=
  file_glob: true
  file:
    - bin/fed-*
    - bin/fed.exe
  on:
    repo: moov-io/fed
    tags: true
    go: 1.14.x
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

notifications:
  slack:
    secure: yIXmC0LCJjGyhwN8ocIJkms/sWJt3zK5tXAyi/+W3eLy1h+AMNSac8aavE297nqfB2kqbPnhZkieVXEOJpEEM4HJ2lli4EqQKpUAoGsWlU/bdLJiWuAQ6xflsB/MPuW2QnM4hptjYNEW7IwMQLBQLRMok4ROBLjaiadBOEpRgjLqTOd5sSRCS5iAMKAuxSEJeQ5lExoa4DDQhiraAOq5pUb5HaAmT8exXAxV1HLbm3hMJPKsFL37DE3ch+Gcx1cW6p34cLykrS6cb9F36A/APdCytYxsmBZRjMYZASYhSIky+DuO1hoAgUlEIx7jTyuF+R+0byR9TCH5x818Cc81JJmCWNrfVOHBnvzIu6G+0MYrdFgVfTOVYqMWzGfooJehPzp1uQiyytqf0djSt0RXxMRev0mwE7q3MHYF7v2AzrrG6Y9zM41qPaZkbVyra1dzwlq/ZxD2gAxCMC2AVVGgA3CDeGPgsTlNWNw7I8RdKMtAM0k6XbYypoJm9jf5XMW6p+gxdpdZccDMuSq0+FAbh5y3Z3IUir3BkWepGPUfrgDKOQ1I9XHtwMDDbhJTWFYN7S5nB7JnU8XXCdG6wAwlRoGyZjslb7mLEUCAFyw0PAvwb5uhd8CATu1xDXy4vgQJaVCjIVLd2B36lmpheSAHalA3FKqxbaTwdFZC7QYxvHw=
