name: Podman

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '>= 1.19.4'
      id: go

    - name: Clone the repository
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Check
      run: make check
      env:
        COVER_THRESHOLD: 70.0
        GOLANGCI_LINTERS: gosec

    - name: Buildah Action
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: moov/fed
        tags: podman-${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Log in to the GitHub Container registry
      if: runner.os == 'Linux' && github.repository == 'moov-io'
      uses: redhat-actions/podman-login@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push to GitHub Container Repository
      if: runner.os == 'Linux' && github.repository == 'moov-io'
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: docker.io
